language: node_js
node_js:
  - "4"
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "5"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "stable"
services:
    - mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    - node_modules
after_success:
    - npm run coveralls
